version: "2"

services:
  python-thrift-server:
    build: ./python-server-thrift
    ports:
      - "9090:9090"

  java-test-client:
    build: ./java-client-thrift
    ports:
      - "8080:8080"
    depends_on:
      - python
    environment:
      - PYTHON_THRIFT_SERVER=python
      - PYTHON_THRIFT_PORT=9090